### ISSUE TITLE
import population data from 'qs:pop'

### ISSUE THREAD

**Issue by missinglink** [pelias/whosonfirst#106]
the following record has a property called `qs:pop` which contains population info, that property may be new and is not currently being checked during import.

- https://whosonfirst.mapzen.com/spelunker/id/404484357/#12/40.6178/-80.2627
- https://github.com/pelias/whosonfirst/blob/master/src/components/extractFields.js#L13-L19

**Comment by orangejulius** [comment]
Sounds good to me. @nvkelso, is this a field we should be using? 

Right now we first look at `gn:population` and then `zs:pop10`. Where should `qs:pop` go in that ordering?

**Comment by trescube** [comment]
Or have a general `mz:population` field would be ideal so we don't have to look in one place for neighbourhoods and another for localities.

**Comment by nvkelso** [comment]
`mz:population` is my preference

**Comment by orangejulius** [comment]
Awesome, I suspect we'll want to handle `qs:pop` ourselves in the meantime (we don't want to rush you to release it when the change on our side is relatively small). Any suggestion for an ordering of the 3 variables?

**Comment by trescube** [comment]
I believe that `zs:pop10` only applies to neighbourhoods.

**Comment by dianashk** [comment]
Update the code to import all 3: `gn:population`, `qs:pop`, `zs:pop10`.
Will switch to `mz:population` when that becomes available.
