### ISSUE TITLE
Importer does not read my pelias.json

### ISSUE THREAD

**Issue by oliverbienert** [pelias/whosonfirst#181]
Hello,

I've setup a pelias.json in my home directory, with a datapath to a local subdir configured, but when I run:

`npm run download -- --admin-only` 

in the whosonfirst subdir, I get an npm error, because it tries to create a directory at `/mnt/pelias`, so probably my config does not get read.
I do probably something wrong or have overlooked the obvious?

**Comment by orangejulius** [comment]
Hey @oliverbienert,
We often mistype the attributes in our `pelias.json` files, or the JSON contents have a slightly incorrect structure that causes things to misbehave. In fact we've started talking about ways to combat this, with some validation of the config.

This is probably what happened here. The easiest way to help is probably if you just paste your entire pelias.json file here, and we'll take a look.

**Comment by missinglink** [comment]
you can use the following command to print your config:

```bash
npm install pelias-config; \
node -e "console.log( require('pelias-config').generate().stringify() );";
```

**Comment by oliverbienert** [comment]
Thank you for your fast reponse!
The error happens on a machine which I have ssh access to at work only, so I can send you the config only tomorrow.
Meanwhile  I'm gonna try and install the thing at my laptop in next couple of hours and eventually come back with some news here.

**Comment by oliverbienert** [comment]
For better or worse, I can't reproduce the behavior at my home box, so I've to wait 'til tomorrow.  

What's not clear to me: Where goes pelias-config? To global `node_modules`, or to `~` or into `pelias/api` subdir? All the importer dirs as well as api, schema etc. live in a subdir `pelias` in my home directory.  

I successfully downloaded whosonfirst data by:
```
npm run download -- --admin-only
```
When importing osm with `"adminLookup": true` , however, I see some errors:
```
2016-12-14T22:19:52.367Z - error: [wof-pip-service:loadJSON] exception occured parsing /home/oliver/data/whosonfirst//data/110/869/4417/1108694417.geojson: Error: ENOENT: no such file or directory, open '/home/oliver/data/whosonfirst//data/110/869/4417/1108694417.geojson'
```
This is just an example line, the error appears for a huge number of apparently wrong pathes.
What I observed is that the above path in deed does not exist, but an almost identical path with the last sub directory `4417` splitted in 2 sub directories:
```
/home/oliver/data/whosonfirst//data/110/869/441/7/1108694417.geojson
```
so the file exists actually.

After each `finished loading xxx features` there also appears the following error:
```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: channel closed
    at process.target.send (internal/child_process.js:523:16)
    at /home/oliver/pelias/openstreetmap/node_modules/pelias-wof-pip-service/src/worker.js:61:13
    at Through2.<anonymous> (/home/oliver/pelias/openstreetmap/node_modules/pelias-wof-pip-service/src/readStream.js:39:7)
    at emitNone (events.js:85:20)
    at Through2.emit (events.js:179:7)
    at finishMaybe (/home/oliver/pelias/openstreetmap/node_modules/through2-sink/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (/home/oliver/pelias/openstreetmap/node_modules/through2-sink/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at Through2.Writable.end (/home/oliver/pelias/openstreetmap/node_modules/through2-sink/node_modules/readable-stream/lib/_stream_writable.js:356:5)
    at Through2.onend (/home/oliver/pelias/openstreetmap/node_modules/readable-stream/lib/_stream_readable.js:504:10)
    at Through2.g (events.js:273:16)
```

Also, I have to exit the process by Ctrl-C.

I have node v7.2.1
and npm 4.0.3

Shall I open a new issue in openstreetmap repository?

**Comment by oliverbienert** [comment]
My bad!
I had the _whosonfirst_ config entry at the wrong place AND I had probably some tabs in the json.
Now _whosonfirst_ import works.

**Comment by dianashk** [comment]
@oliverbienert: Glad it's working now! I'll just add that you can always specify the config path on the command line when running the importer or any other Pelias component. This is my preferred approach when running locally because it allows me to keep different config files for each component and not have to dig around my machine to find it. 

`PELIAS_CONFIG=./my config.json npm run download`

Happy geocoding!
