### ISSUE TITLE
why no 'macrohood' in bundlelist?

### ISSUE THREAD

**Issue by missinglink** [pelias/whosonfirst#213]
hey, just wondering if there is a reason why `macrohood` is not included in the list of `hierarchyRoles` in `src/bundleList.js`?

**Comment by trescube** [comment]
IIRC, macrohoods were empty when WOF integration work was initially done.  We should do some research into which macrohoods are "valid" (culturally known places).

**Comment by orangejulius** [comment]
Yeah we should definitely add macrohoods. It looks like some internal shuffling has happened in WOF data, and records that were [previously neighbourhoods](https://whosonfirst.mapzen.com/spelunker/id/85887443/#14/37.7594/-122.4127) are now [macrohoods](https://whosonfirst.mapzen.com/spelunker/id/1108830809/#14/37.7604/-122.4181)
