### ISSUE TITLE
Add flag that stops import for missing data files

### ISSUE THREAD

**Issue by trescube** [pelias/whosonfirst#214]
See #209 and pelias/wof-admin-lookup#102

Add a configuration parameter in `imports.whosonfirst` (perhaps `missingDataIsFatal`) that defaults to `false`.  Defaulting to `false` means that users spinning up their own Pelias instances wouldn't have to set anything additional but we would (far less impactful) for our production builds.

**Comment by orangejulius** [comment]
This was done in https://github.com/pelias/whosonfirst/pull/229
