### ISSUE TITLE
Refactor bundleList and tests to not contact live website

### ISSUE THREAD

**Issue by trescube** [pelias/whosonfirst#226]
The bundleList code [contacts WOF](https://github.com/pelias/whosonfirst/blob/master/src/bundleList.js#L64) for the bundle list.  This should be refactored to inject the bundle list URL so that the test can operate offline.

**Comment by orangejulius** [comment]
Additionally, it would be great if the bundle URL, and WOF URLs in general, were configurable via `pelias.json` or environment variable. Using a WOF snapshot could be useful for many instances of pelias that want greater control over the source of their data.
