### ISSUE TITLE
Allow user to whitelist postalcode countries

### ISSUE THREAD

**Issue by trescube** [pelias/whosonfirst#230]
The whosonfirst importer currently forces a user looking to import postalcodes to download and import postal codes from literally every single one of the 213 countries.  That seems a bit excessive if, say, they're only interesting in importing Germany postal codes.  Perhaps the importer can look for an array in pelias config of whitelisted country ISO2's to import.  My personal use case is that I'm just trying to run a test import and I'm hacking the code a bit to just run a single country.

**Comment by orangejulius** [comment]
As of https://github.com/pelias/whosonfirst/pull/487 and the https://github.com/pelias/whosonfirst/releases/tag/v4.0.0 release, we support `countryCode` as  config parameter, and postal codes are only downloaded on a per-country basis! :tada:
