### ISSUE TITLE
Download by placeId

### ISSUE THREAD

**Issue by rahimramezanian** [pelias/whosonfirst#255]
I would love to download data for France. I found these commands
`npm run download --importPlace FR`
and 
`node utils/download_data_filtered/downloadPlaces.js FR`
but it seems they are not working the first downloads a lot of data.
The seconds downloads nothing.
Sorry it is not clear from the readme how to download the data.

Thanks.

**Comment by tigerlily-he** [comment]
Hi @rahimramezanian! Data downloads are controlled by a [config file](https://github.com/pelias/config/blob/master/config/defaults.json) called `pelias.json`. 

1. In your home directory (or anywhere), create a file called `pelias.json` and specify the `datapath`, `api_key` and `importPlace`. You can also configure additional settings, such as [importing postal codes or venues](https://github.com/pelias/whosonfirst#configuration). 
```
{
  "imports": {
     "whosonfirst": {
       "datapath": "/path/to/data",
       "api_key": "mapzen-xxxxxx",
       "importPlace":"85633147"
     }
  }
}
```
To download data for [France](https://whosonfirst.mapzen.com/spelunker/search/?q=france), Whosonfirst ID is `85633147`. (We currently do not support ISO2 codes) You can get the Whosonfirst ID for any place with the [Spelunker tool](https://whosonfirst.mapzen.com/spelunker/).
 
2. You will need an API key. Visit the [Mapzen Developers dashboard](https://mapzen.com/dashboard) to get a working api key.

3. Export the environment variable for the path to your `pelias.json` file and run the import.
```
$ PELIAS_CONFIG=<path-to-config> npm run download
```

**Comment by rahimramezanian** [comment]
Hi @tigerlily-he. Thank you.

**Comment by tigerlily-he** [comment]
We're always looking to improve our documentation and we love contribution from the community. Would you like to create a PR in the README to clarify the import process?
