### ISSUE TITLE
Postal code with embedded comma

### ISSUE THREAD

**Issue by trescube** [pelias/whosonfirst#3]
All streets in Front Royal, VA have postal code "22,630" (embedded comma).

**Comment by stephenkhess** [comment]
Some more examples:

23,922
22,046
24,271
24,382
24,016
23,602
23,061
23,661
22,901
23,805
22,601
22,401
24,541
20,110

**Comment by riordan** [comment]
@trescube is this still an issue?

**Comment by trescube** [comment]
Nope, @orangejulius took care of this with https://github.com/openaddresses/openaddresses/pull/1522 (assuming the build eventually passes)
