### ISSUE TITLE
Importer needs to use WOF inventory.json file

### ISSUE THREAD

**Issue by orangejulius** [pelias/whosonfirst#384]
Currently, this importer gathers information about WOF data for download from https://dist.whosonfirst.org/bundles/index.txt

The WOF team is migrating to storing this information in a richer JSON format at https://dist.whosonfirst.org/bundles/inventory.json.

We need to update this importer to use that new format.

**Comment by Joxit** [comment]
With https://github.com/pelias/whosonfirst/pull/417, I added the inventory.json support for the SQLite download only. I can back-port this feature for the bundle download.

**Comment by orangejulius** [comment]
Lets consider this fixed by #417 :)

Hopefully we can soon deprecate the bundle download code.
