### ISSUE TITLE
Downloader and Importer bundle name mismatch

### ISSUE THREAD

**Issue by richardcalahan** [pelias/whosonfirst#388]
I'm just getting started with downloading and importing WOF data using the production branch. Looks like the importer incorrectly attempts to translate a bundle name to a meta csv name. 

The result is errors like:

`Error: ENOENT: no such file or directory, open '[datapath]/meta/whosonfirst-data-ocean-latest.tar.bz2'`

I'm new to this project, so I may be missing other considerations, but simply removing '-bundle' from the [replace function](https://github.com/pelias/whosonfirst/blob/production/import.js#L26) resolves the error for me.

**Comment by neoInt** [comment]
Same here. I think that the filenames of the whosonfirst dataset has been changed and the replace function has to be updated to the new names.

**Comment by missinglink** [comment]
the whosonfirst team changed some of the filenames, @orangejulius did we already land a fix for this? I remember we talked about it.

**Comment by orangejulius** [comment]
Hey everyone,
Thanks for the reports.

We fixed some of the results of this change in https://github.com/pelias/whosonfirst/pull/385, but it indeed looks like that line was missed.

@richardcalahan if that change fixes it for you, a PR would be most appreciated :)

**Comment by richardcalahan** [comment]
OK all set. #389
