### ISSUE TITLE
Wrong base_url in downloader?

### ISSUE THREAD

**Issue by nilsnolde** [pelias/whosonfirst#400]
On branch `production`:

When using `sudo npm run download` on WOF, it seems to try to download from the wrong URL, example output:

> error downloading wof-postalcode-au-latest-bundle.tar.bz2 bundle: Error: Command failed: curl https://dist.whosonfirst.org/bundles/wof-postalcode-au-latest-bundle.tar.bz2 | tar -xj --strip-components=1 --exclude=README.txt -C /srv/pelias_importer_ext/data/wof && mv /srv/pelias_importer_ext/data/wof/wof-postalcode-au-latest.csv /srv/pelias_importer_ext/data/wof/meta
> bzip2: (stdin) is not a bzip2 file.
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now

The URL [https://dist.whosonfirst.org/bundles/wof-postalcode-au-latest-bundle.tar.bz2]() does not exist, but should be [https://dist.whosonfirst.org/bundles/whosonfirst-data-postalcode-au-latest-bundle.tar.bz2](). That's weird, since [the bundle index](https://dist.whosonfirst.org/bundles/index.txt) is correct and as far as I can tell, that's how the downloader builds the URLs.

What am I missing here?

**Comment by orangejulius** [comment]
Hey Nils,
The whosonfirst importer downloads a cached copy of the bundle list. You should find it in the root of the whosonfirst data directory, and should remove it. We really need to fix that, thanks for reminding me.

**Comment by nilsnolde** [comment]
Hey Julian,
thx for your quick and helpful answer! I found the file in `wof_root/meta`. I deleted it and restarted the importer. However, it seems to download the wrong bundle index file. It was in fact the same file that I deleted earlier. When I manually `wget` the index file, it manages to download properly, but then fails at moving the untarred CSVs, because the filename is still pointing to the archive. Example:

> error downloading whosonfirst-data-ocean-latest.tar.bz2 bundle: Error: Command failed: curl https://dist.whosonfirst.org/bundles/whosonfirst-data-ocean-latest.tar.bz2 | tar -xj --strip-components=1 --exclude=README.txt -C /srv/pelias_importer_ext/data/wof && mv /srv/pelias_importer_ext/data/wof/whosonfirst-data-ocean-latest.tar.bz2 /srv/pelias_importer_ext/data/wof/meta

> mv: cannot stat '/srv/pelias_importer_ext/data/wof/whosonfirst-data-ocean-latest.tar.bz2': No such file or directory

It should read 

```bash
&& mv /srv/pelias_importer_ext/data/wof/whosonfirst-data-ocean-latest.csv /srv/pelias_importer_ext/data/wof/meta
```
I assume?

**Comment by orangejulius** [comment]
Huh, that is interesting. Can you try some or all of the following things that have been known to cause similar issues?
- `rm -rf node_modules; npm install` (old NPM modules commonly cause issues)
- `rm -rf` your entire wof data dir and download completely fresh
- ensure you're on the latest production code
- try the master branch as well

**Comment by nilsnolde** [comment]
Thanks, @orangejulius,  the 2nd point actually worked, didn't have to try the `master` branch.
