### ISSUE TITLE
custom WOF méta files to import from

### ISSUE THREAD

**Issue by Devmaticz** [pelias/whosonfirst#418]
Hello all,

Trying to get the PIP service, working with m'y own data formatée like WOF ones, to be able to use the WOF importer.

Does anyone managed something like this.

And is there any tool that can help me creat thos files.

Let the force be with you.

**Comment by orangejulius** [comment]
Hey @Devmaticz,
We [recently](https://github.com/pelias/whosonfirst/pull/412) added support for custom download locations for WOF. It still requires quite a bit of work to create a custom dataset, as it has to mirror the WOF format exactly, but it at least opens up possibilities.

In the future, we hope to expand on this to support custom administrative areas across all of Pelias.
