### ISSUE TITLE
whosonfirst importer is not importing sqlite databases

### ISSUE THREAD

**Issue by Hessi9** [pelias/whosonfirst#426]
The current code of the whosonfirst importer is downloading some sqlite databases, but is importing only the old style bundles data. Maybe there are some new still undocumented config options I haven't found...

**Comment by missinglink** [comment]
This feature is being actively developed, it's currently in testing, I hope we can merge it soon.
see: https://github.com/pelias/whosonfirst/pull/417

The sqlite files are currently used for regional extracts (when using the `whosonfirst.importPlaces` config option), so, for instance, our [pelias/docker](https://github.com/pelias/docker) configs use that.

We're hoping to switch to using the sqlite files as our default distribution and moving away from the bundles.

**Comment by Hessi9** [comment]
With the newes commit from this night it is working now.
Need to be activated by config: whosonfirst.sqlite = true

**Comment by Joxit** [comment]
Yes, for the pip-service supports, you will wait the merge of https://github.com/pelias/wof-admin-lookup/pull/249 :smile:

**Comment by missinglink** [comment]
I just merged https://github.com/pelias/wof-admin-lookup/pull/249 so this feature is now ready for testing.

**Comment by missinglink** [comment]
pip-service updated in https://github.com/pelias/pip-service/pull/106
