### ISSUE TITLE
Remove sqlite index creation

### ISSUE THREAD

**Issue by otbutz** [pelias/whosonfirst#453]
https://github.com/pelias/whosonfirst/blob/31112fdaa9d385ead1ab6510512360cec03a8f13/src/components/sqliteStream.js#L9-L14

The mentioned PR has already been merged: https://github.com/whosonfirst/go-whosonfirst-sqlite-features/pull/4

**Comment by missinglink** [comment]
I just checked and unfortunately, that index is still not available in the sqlite files located at https://dist.whosonfirst.org/sqlite/.

I suspect there is a configuration problem on the server which generates the dist files, it possibly hasn't been updated:
https://github.com/whosonfirst/go-whosonfirst-sqlite-features/pull/4#issuecomment-500104944

**Comment by orangejulius** [comment]
All the country-specific download files now have this index. The global file (`whosonfirst-data-latest`) still doesn't, but we are close to being able to remove this code.

**Comment by missinglink** [comment]
This will be possible once https://github.com/pelias/whosonfirst/pull/487 is merged.

**Comment by orangejulius** [comment]
Finally done in #487. This importer now downloads data from builds sponsored by Geocode Earth, which are built with the `spr_obsolete` index. :tada:
