### ISSUE TITLE
Default `whosonfirst.sqlite` to true

### ISSUE THREAD

**Issue by orangejulius** [pelias/whosonfirst#460]
We have been testing the SQLite download option introduced in https://github.com/pelias/whosonfirst/pull/417 for some time, and it appears to be pretty solid.

As far as I know, the SQLite databases are the preferred distribution method for WOF data going forward.

What is left before we consider setting `whosonfirst.sqlite` to true by default?

**Comment by orangejulius** [comment]
There's at least one blocker for this: the wof-admin-lookup tests currently fail when `sqlite` is set to `true`: https://github.com/pelias/wof-admin-lookup/issues/262

**Comment by Joxit** [comment]
Now that pelias/wof-admin-lookup#262 is fixed, I think we can set SQLite by default :smile:.

**Comment by orangejulius** [comment]
We've done lots of testing with SQLite DBs recently. They are definitely the way of the future and already work well today.

Two PRs left to merge before we can do this:

- https://github.com/pelias/placeholder/pull/157 (and https://github.com/pelias/placeholder/pull/169 which improves it) to add SQLite support to Placeholder
- #477 to avoid downloading both the full planet and country DBs from dist.whosonfirst.org

Should happen soon!
