### ISSUE TITLE
Import concordances

### ISSUE THREAD

**Issue by bboure** [pelias/whosonfirst#475]
Hi there,

I wish you all a Happy geocoding 2020!

I might be in a need to use some extra tags coming from WOF in some administrative areas.
In my case, I am interested into the `wikidata`/`wikipedia` tags under `wof:concordances`.

The `osm` importer imports such tags in the `addendum` field, but I see that `wof` doesn't.

Would it make sense to import them as well here?

Thank you!

**Comment by orangejulius** [comment]
Hi @bboure,

Happy new year to you too!

Adding concordances to WOF records would be excellent. While it's probably not too difficult to add them to records in Elasticsearch as done in the OSM importer, many queries to Pelias will not use that data, as described in https://github.com/pelias/pelias/issues/819. We haven't decided how to solve that issue yet, but it's a discussion we should revive.
