### ISSUE TITLE
Got 403 on import resource

### ISSUE THREAD

**Issue by kmadenski** [pelias/whosonfirst#479]
Hey team! 

I got 403 on https://dist.whosonfirst.org/sqlite/whosonfirst-data-venue-pl-latest.db.bz2 resource.
It is intentional?

**Comment by missinglink** [comment]
Hi @kmadenski, we don't control the `whosonfirst.org` domain but I've heard from their team that they've been getting a lot of abuse recently which has resulted in increased costs on the project (which is funded through donations).

Could you please check that your scripts are caching correctly and not performing unnecessary requests?

I've just started building our own WOF data for Pelias users, it's much more current.

For now it's hosted on my dev server `synergy.io` but be aware that the domain name may change without warning so I'd avoid hard-coding the domain in any configs for now.
https://wof.synergy.io/sqlite/

Feel free to take what you need, please let me if you find it useful, we are considering adding them as an alternative to the `dist.whosonfirst.org` at https://geocode.earth/data

**Comment by kmadenski** [comment]
Thanks for source. I can download data for every country, but where can i get base meta files like whosonfirst-data-ocean-latest.csv? This files is required for wof importer.

**Comment by kmadenski** [comment]
Thx for great source.

I see that synergy.io convension for meta (folder bundles) is not working with pelias wof importer. It wants whosonfirst-data-**ocean**-latest.csv. In source we got ocean.csv.

**Comment by missinglink** [comment]
@kmadenski would you be interested in opening a PR to fix it?

It's a single line change: https://github.com/pelias/wof/blob/master/stream/bundle.js#L68

**Comment by missinglink** [comment]
closed by https://github.com/pelias/wof/pull/8
