### ISSUE TITLE
Name change: Ocean County

### ISSUE THREAD

**Issue by missinglink** [pelias/whosonfirst#49]
there is a regression **on dev** for `"county": "Ocean County"`, it's now showing as `"county": "Ocean"`.

is it possible that in WOF the suffix `"County"` has been removed because it's redundant?

- http://pelias.github.io/compare/#/v1/search%3Flayer=neighbourhood&text=Vista%20Center
- https://whosonfirst.mapzen.com/spelunker/id/102081485/

```bash
 ✘ regression [13] "{"text":"Vista Center","layers":"neighbourhood"}": score 4 out of 6
  diff:
    county
      expected: Ocean County
      actual:   Ocean
    unexpected result found
  ✘ regression [14] "{"text":"Yadkin Trail","layers":"neighbourhood"}": score 4 out of 6
  diff:
    county
      expected: Moore County
      actual:   Moore
    unexpected result found
  ✘ regression [15] "{"text":"Hillside, Santa Clara","layers":"neighbourhood"}": score 5 out of 6
  diff:
    county
      expected: Santa Clara County
      actual:   Santa Clara
```

**Comment by missinglink** [comment]
cc/ @riordan we spoke about this last week in our 1:1.

I think it's not a real regression, I can just update the tests with the new names right?

**Comment by missinglink** [comment]
after talking to @dianashk, we would like to have `Ocean County` instead of `Ocean` and so the tests should stay the same, a PR has been made to fix it, awaiting new dev build.

ref: https://github.com/pelias/whosonfirst/issues/43

**Comment by trescube** [comment]
This will be fixed in next data build when the WOF importer uses the `qs:a2_alt name` for US counties.

**Comment by dianashk** [comment]
Fixed. Hooray!
