### ISSUE TITLE
Getting the message: "debug: [wof-admin-lookup] no country"

### ISSUE THREAD

**Issue by dmaj** [pelias/whosonfirst#517]
I import addresses for Germany (oa, osm).
I'm useing "Whosonfirst" data for  the whole planet. When importing oa and osm I get hundreds of messages: _debug: [wof-admin-lookup] no country lon=12.847481, lat=50.448679, ...._
I have checked many of the output coordinates. They are all very close to borders or to the coast.

Unfortunately I am not yet familiar enough with the data structures to find the problem myself. Is this a problem of the importers? Or is the problem to be found in the "Whosonfirst" data? The boundaries can only be approximated with polygons, so there could be addresses in the gaps.

**Comment by missinglink** [comment]
As you mentioned the problem is either that the points aren't in Germany or don't lie within the Germany polygon.

It's impossible to comment further without information about exactly which data you're importing and how you have configured pelias.

**Comment by orangejulius** [comment]
Adding on to what @missinglink said, we don't generally consider this debug message to be a problem. Certainly if there is a particular record not being associated with a country an you expect it should, examine the record and the polygon for the country to make sure they match up (either could have invalid data).

But, in general, this any any other `debug` message is safe to ignore. In fact, I wonder if this is another one we want to consider removing?
