### ISSUE TITLE
Add population support from `zs:pop10`

### ISSUE THREAD

**Issue by trescube** [pelias/whosonfirst#59]
Neighborhoods (especially in NYC) lack a `gn:population` field which is causing adverse effects since our scoring logic punishes results with popularity but no population (eg - Chelsea).  The whosonfirst importer should use the `zs:pop10` value for population when `gn:population` doesn't exist.  Also, of the 43,571 WOF records containing `zs:pop10`, 1,670 have a `0` value.  In cases where `zs:pop10` has a `0` value, it should be ignored so that our scoring logic can give it a default of `1`.

**Comment by orangejulius** [comment]
Awesome. How many `gn:population` values are there, and how many have both?

**Comment by trescube** [comment]
I haven't done an complete analysis but the appear to be mutually exclusive.
