### ISSUE TITLE
import bbox for Who's on First geometry

### ISSUE THREAD

**Issue by riordan** [pelias/whosonfirst#8]
_From @missinglink on July 30, 2015 17:53_

in lieu of providing the full geometry for countries/states/regions and all the issues involved with that we can at least provide a bbox of the geometry in order for the client to be able to zoom to a level which fully encompasses the entity.

http://geojson.org/geojson-spec.html#bounding-boxes

_Copied from original issue: pelias/quattroshapes#29_

**Comment by riordan** [comment]
Good and YES!

Question: can we address this now (so it can be part of Erasermap 1) or does it make sense to tackle shortly thereafter and get added in a later build.

It's very useful when retargeting to another administrative area, but not necessary for launch.

**Comment by riordan** [comment]
_From @missinglink on August 27, 2015 11:40_

considering our current workload I would say that we mark it as 'high priority but not right now'

**Comment by riordan** [comment]
_From @burritojustice on October 8, 2015 17:4_

this would be nice for the leaflet plugin demo when you search for a country and end up in a vast white expanse because of refill and the default zoom level 12 (which, for the Northwest Territories, while accurate, is confusing. kansas too...)

**Comment by riordan** [comment]
What's the matter with Kansas? Or Northwest Territories?

I would love to see this. I think the question that behooves us now is "how
long will it take us to do this in 4shapes vs how long will it take us to
do WoF including this?"

If its something we can incorporate in a day or so (ideally w/o breaking
the schema), I'd love to see it happen sooner rather than later.

On Thu, Oct 8, 2015 at 1:04 PM, burritojustice <notifications@github.com>
wrote:

> this would be nice for the leaflet plugin demo when you search for a
> country and end up in a vast white expanse because of refill and the
> default zoom level 12 (which, for the Northwest Territories, while
> accurate, is confusing. kansas too...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/quattroshapes/issues/29#issuecomment-146625185>
> .
>



-- 
David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan <https://twitter.com/riordan> | gpg 235D9DC95EF6277C
<https://keybase.io/riordan>
Mapzen | https://mapzen.com | @mapzen <https://twitter.com/search>

**Comment by riordan** [comment]
Now applies / should be fixed by Who's on First, rather than 4Shapes.

**Comment by stephenkhess** [comment]
Fixed #13

**Comment by orangejulius** [comment]
This was fixed in #13, will be in production shortly

**Comment by riordan** [comment]
While fixed in #13, that won't be going out to production just yet... We're doing a little test and hopefully should hit in the first week or two of 2016

cc: @louh
