### ISSUE TITLE
Venue data

### ISSUE THREAD

**Issue by curiousc0w** [pelias/whosonfirst#93]
Hi,

I was wondering if you have an repo for venue data for all the countries/regions rather than downloading each sub region at a time?

Thank you.

**Comment by trescube** [comment]
Hi,

That's a question for the data team: https://github.com/whosonfirst

I know that they maintain a bundles site at https://whosonfirst.mapzen.com/bundles/ but I don't see a bundle for venues yet.

**Comment by curiousc0w** [comment]
@trescube Thank you! I didn't see a bundles page but the script at the bottom helps!
